"""Add ticket documents table

Revision ID: 26453f86e6b8
Revises: b1e3f7a9c025
Create Date: 2026-02-23 04:06:56.791085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26453f86e6b8'
down_revision: Union[str, Sequence[str], None] = 'b1e3f7a9c025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_documents_file_id'), 'ticket_documents', ['file_id'], unique=True)
    op.create_index(op.f('ix_ticket_documents_id'), 'ticket_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_documents_id'), table_name='ticket_documents')
    op.drop_index(op.f('ix_ticket_documents_file_id'), table_name='ticket_documents')
    op.drop_table('ticket_documents')
    # ### end Alembic commands ###
