"""expand_document_system_v2

Revision ID: baa660442beb
Revises: 26453f86e6b8
Create Date: 2026-02-23 10:03:36.997638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa660442beb'
down_revision: Union[str, Sequence[str], None] = '26453f86e6b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbound_delivery_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['ticket_documents.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_delivery_contents_id'), 'outbound_delivery_contents', ['id'], unique=False)
    op.create_table('voucher_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['ticket_documents.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_contents_id'), 'voucher_contents', ['id'], unique=False)
    op.create_table('voucher_variable_qty_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['ticket_documents.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_variable_qty_contents_id'), 'voucher_variable_qty_contents', ['id'], unique=False)
    op.create_table('voucher_with_explanation_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['ticket_documents.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_with_explanation_contents_id'), 'voucher_with_explanation_contents', ['id'], unique=False)
    op.create_table('voucher_with_title_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['ticket_documents.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_with_title_contents_id'), 'voucher_with_title_contents', ['id'], unique=False)
    op.add_column('ticket_documents', sa.Column('template_name', sa.String(), nullable=False))
    op.drop_column('ticket_documents', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_documents', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('ticket_documents', 'template_name')
    op.drop_index(op.f('ix_voucher_with_title_contents_id'), table_name='voucher_with_title_contents')
    op.drop_table('voucher_with_title_contents')
    op.drop_index(op.f('ix_voucher_with_explanation_contents_id'), table_name='voucher_with_explanation_contents')
    op.drop_table('voucher_with_explanation_contents')
    op.drop_index(op.f('ix_voucher_variable_qty_contents_id'), table_name='voucher_variable_qty_contents')
    op.drop_table('voucher_variable_qty_contents')
    op.drop_index(op.f('ix_voucher_contents_id'), table_name='voucher_contents')
    op.drop_table('voucher_contents')
    op.drop_index(op.f('ix_outbound_delivery_contents_id'), table_name='outbound_delivery_contents')
    op.drop_table('outbound_delivery_contents')
    # ### end Alembic commands ###
