"""details

Revision ID: fada0e1abce7
Revises: 10a2fdac70e7
Create Date: 2026-03-10 18:56:15.002259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fada0e1abce7'
down_revision: Union[str, Sequence[str], None] = '10a2fdac70e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'details')
    op.drop_column('tickets', 'remarks')
    # ### end Alembic commands ###
